name: projo-backend

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 1234qwer5678tyui
      POSTGRES_DB: db-projo

volumes:
  projo-data:
    name: projo-data-volume
